name: Build & Push Docker Image

on:
  push:
    branches: [main]
    paths:
      - '!examples/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Generate Version
        id: version
        run: |
          VERSION="$(git describe --tags --always --abbrev=7 --match='v[0-9]*.[0-9]*.[0-9]*')"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

          echo "### Workflow Run" >> "$GITHUB_STEP_SUMMARY"
          echo "**Version**" >> "$GITHUB_STEP_SUMMARY"
          echo "$VERSION" >> "$GITHUB_STEP_SUMMARY"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Crossplane CLI
        run: "[ -f crossplane ] || curl -sL https://raw.githubusercontent.com/crossplane/crossplane/${{vars.CROSSPLANE_VERSION_TAG }}/install.sh | sh"
        shell: bash

      - name: Add Crossplane to PATH
        run: echo "$PWD" >> $GITHUB_PATH

      - name: Build xpkg
        run: crossplane xpkg build -o catalog-items.xpkg
        working-directory: package

      - name: Push xpkg
        run: crossplane xpkg push -f catalog-items.xpkg ${{ vars.REGISTRY_URL }}/platformplane/platform-catalog-azure:${{ steps.version.outputs.version }}
        working-directory: package
